<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260808042659 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE usuario_login (IDuser INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usuario VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL, nivel_acceso INT NOT NULL, nombre VARCHAR(150) NOT NULL, cargo VARCHAR(150) NOT NULL, interno VARCHAR(30) DEFAULT NULL, correo VARCHAR(180) DEFAULT NULL, imagen VARCHAR(255) DEFAULT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, estado BOOLEAN NOT NULL, habilitado BOOLEAN NOT NULL, PRIMARY KEY (IDuser))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE usuario_login');
    }
}
